/* Generated By:JJTree: Do not edit this line. ASTkey.java */

package com.thedeanda.javajson.parser;

public class ASTkey extends SimpleNode {
	String val;

	public ASTkey(int id) {
		super(id);
	}

	public ASTkey(JsonParser p, int id) {
		super(p, id);
	}

	@Override
	protected void interpret() {
		((SimpleNode) parent).push(fixString(val));
	}

	private String fixString(String s) {
		String ret = s;

		if (s == null || s.length() < 2)
			return ret;

		if (ret.startsWith("\"") && ret.endsWith("\"")) {
			return ASTstring.fixString(s);
		}

		if (ret.startsWith("'") && ret.endsWith("'")) {
			return ASTstring.fixString(s);
		}

		return ret;
	}
}
