/* Generated By:JJTree: Do not edit this line. ASTnumber.java */

package com.thedeanda.javajson.parser;

public class ASTnumber extends SimpleNode {
	String val;

	public ASTnumber(int id) {
		super(id);
	}

	public ASTnumber(JsonParser p, int id) {
		super(p, id);
	}

	@Override
	protected void interpret() {
		Object o;
		if (val.contains("."))
			o = new Double(val);
		else o = new Long(val);
		
		((SimpleNode) parent).push(o);
	}

}
