/* Generated By:JJTree: Do not edit this line. ASTobject.java */

package com.thedeanda.javajson.parser;

import com.thedeanda.javajson.JsonObject;

public class ASTobject extends SimpleNode {
	JsonObject json = new JsonObject();

	public ASTobject(int id) {
		super(id);
	}

	public ASTobject(JsonParser p, int id) {
		super(p, id);
	}

	@Override
	protected void interpret() {
		if (children != null) {
			for (int i = 0; i < children.length; i++) {
				if (children[i] instanceof SimpleNode) {
					SimpleNode node = (SimpleNode) children[i];
					node.interpret();
				}
			}
		}

		((SimpleNode) parent).push(json);
	}

	@Override
	protected void push(Object o) {
		// System.out.println("pushing to json object: " +
		// o.getClass().getSimpleName());
		if (o instanceof TMember) {
			TMember m = (TMember) o;
			if (m.value instanceof ASTarray)
				json.put(m.key, ((ASTarray) m.value).array);
			else
				json.put(m.key, m.value);
		}
	}
}
