/* Generated By:JJTree: Do not edit this line. ASTparse.java */

package com.thedeanda.javajson.parser;

import com.thedeanda.javajson.JsonArray;
import com.thedeanda.javajson.JsonObject;

public class ASTparse extends SimpleNode {
	JsonObject val;
	JsonArray arr;

	public ASTparse(int id) {
		super(id);
	}

	public ASTparse(JsonParser p, int id) {
		super(p, id);
	}

	public JsonObject getJsonObject() {
		interpret();
		return val;
	}
	
	public JsonArray getJsonArray() {
		interpret();
		return arr;
	}

	@Override
	protected void interpret() {
		for (int i = 0; i < children.length; i++) {
			if (children[i] instanceof SimpleNode) {
				((SimpleNode) children[i]).interpret();
			}
		}
	}

	@Override
	protected void push(Object o) {
		if (o instanceof JsonObject)
			val = (JsonObject) o;
		else if (o instanceof JsonArray)
			arr = (JsonArray) o;
	}
}
