/* Generated By:JJTree&JavaCC: Do not edit this line. JsonParserConstants.java */
package com.thedeanda.javajson.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JsonParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 9;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 10;
  /** RegularExpression Id. */
  int HEX_DIGIT = 11;
  /** RegularExpression Id. */
  int HEX_LITERAL = 12;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 13;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 14;
  /** RegularExpression Id. */
  int EXPONENT = 15;
  /** RegularExpression Id. */
  int TRUE_LITERAL = 16;
  /** RegularExpression Id. */
  int FALSE_LITERAL = 17;
  /** RegularExpression Id. */
  int NULL_LITERAL = 18;
  /** RegularExpression Id. */
  int KEY_LITERAL = 19;
  /** RegularExpression Id. */
  int STRING_LITERAL = 20;
  /** RegularExpression Id. */
  int STRING_LITERAL_SINGLE_QUOTES = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_DIGIT>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<KEY_LITERAL>",
    "<STRING_LITERAL>",
    "<STRING_LITERAL_SINGLE_QUOTES>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
  };

}
