/* Generated By:JavaCC: Do not edit this line. JsonParserTreeConstants.java Version 6.0_1 */
package com.thedeanda.javajson.parser;

public interface JsonParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTOBJECT = 1;
  public int JJTARRAY = 2;
  public int JJTMEMBERS = 3;
  public int JJTELEMENTS = 4;
  public int JJTVALUE = 5;
  public int JJTKEY = 6;
  public int JJTSTRING = 7;
  public int JJTNUMBER = 8;


  public String[] jjtNodeName = {
    "parse",
    "object",
    "array",
    "members",
    "elements",
    "value",
    "key",
    "string",
    "number",
  };
}
/* JavaCC - OriginalChecksum=4c210b7883cc8c3db42aec37bc324cb2 (do not edit this line) */
