/* Generated By:JJTree: Do not edit this line. ASTparse.java */

package net.sourceforge.javajson.parser;

import net.sourceforge.javajson.JsonObject;

public class ASTparse extends SimpleNode {
	JsonObject val;

	public ASTparse(int id) {
		super(id);
	}

	public ASTparse(JsonParser p, int id) {
		super(p, id);
	}

	public JsonObject getJsonObject() {
		interpret();
		return val;
	}

	@Override
	protected void interpret() {
		for (int i = 0; i < children.length; i++) {
			if (children[i] instanceof SimpleNode) {
				((SimpleNode) children[i]).interpret();
			}
		}
	}

	@Override
	protected void push(Object o) {
		val = (JsonObject) o;
	}
}
