/* Generated By:JJTree: Do not edit this line. ASTarray.java */

package net.sourceforge.javajson.parser;

import net.sourceforge.javajson.JsonArray;

public class ASTarray extends SimpleNode {
	JsonArray array = new JsonArray();

	public ASTarray(int id) {
		super(id);
	}

	public ASTarray(JsonParser p, int id) {
		super(p, id);
	}

	@Override
	protected void interpret() {
		if (children != null) {
			for (int i = 0; i < children.length; i++) {
				if (children[i] instanceof SimpleNode) {
					SimpleNode node = (SimpleNode) children[i];
					node.interpret();
				}
			}
		}

		((SimpleNode) parent).push(array);
	}

	@Override
	protected void push(Object o) {
		array.add(o);
	}
}
