/* Generated By:JJTree: Do not edit this line. ASTkey.java */

package net.sourceforge.javajson.parser;

public class ASTkey extends SimpleNode {
	String val;

	public ASTkey(int id) {
		super(id);
	}

	public ASTkey(JsonParser p, int id) {
		super(p, id);
	}

	@Override
	protected void interpret() {
		((SimpleNode) parent).push(fixString(val));
	}

	private String fixString(String s) {
		String ret = s;
		
		if (ret.length() >= 2 && ret.startsWith("\"") && ret.endsWith("\""))
			ret = ret.substring(1, ret.length() - 1);
		
		if (ret.length() >= 2 && ret.startsWith("'") && ret.endsWith("'"))
			ret = ret.substring(1, ret.length() - 1);
				
		return ret;
	}
}
