/* Generated By:JJTree: Do not edit this line. ASTstring.java */

package net.sourceforge.javajson.parser;

public class ASTstring extends SimpleNode {
	String val;

	public ASTstring(int id) {
		super(id);
	}

	public ASTstring(JsonParser p, int id) {
		super(p, id);
	}

	@Override
	protected void interpret() {
		((SimpleNode) parent).push(ASTstring.fixString(val));
	}
	
	/** Removes escapes from string and returns normal string */
	protected static String fixString(String s) {
		String ret = s.substring(1, s.length()-1);
		//String t = ret;
		ret = ret.replace("\\\"", "\"");
		ret = ret.replace("\\'", "'");
		
		ret = ret.replace("\\b", "\b");
		ret = ret.replace("\\f", "\f");
		ret = ret.replace("\\n", "\n");
		ret = ret.replace("\\r", "\r");
		ret = ret.replace("\\t", "\t");
		ret = ret.replace("\\/", "/");
		ret = ret.replace("\\\\", "\\");
		
		//System.out.println(s + " " + ret);
		return ret;
	}
}
