/* Generated By:JJTree: Do not edit this line. ASTstring.java */

package net.sourceforge.javajson.parser;

public class ASTstring extends SimpleNode {
	String val;

	public ASTstring(int id) {
		super(id);
	}

	public ASTstring(JsonParser p, int id) {
		super(p, id);
	}

	@Override
	protected void interpret() {
		((SimpleNode) parent).push(fixString(val));
	}
	
	/** Removes escapes from string and returns normal string */
	private String fixString(String s) {
		String ret = s.substring(1, s.length()-1);
		String t = ret;
		ret = ret.replaceAll("\\\\\"", "\"");
		ret = ret.replaceAll("\\\\'", "'");
		
		ret = ret.replaceAll("\\\\b", "\b");
		ret = ret.replaceAll("\\\\f", "\f");
		ret = ret.replaceAll("\\\\n", "\n");
		ret = ret.replaceAll("\\\\r", "\r");
		ret = ret.replaceAll("\\\\t", "\t");
		
		//System.out.println(t + " " + ret);
		return ret;
	}
}
